apiVersion: v1
kind: Pod
metadata:
  name: python-app-pod
  labels:
    app: python-app
spec:
  containers:
    - name: python-app
      image: suds123/python-app:v1
      ports:
        - containerPort: 8000
